CREATE TABLE COMPANY
(
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE USER_COMPANY
(
    CompanyId INT NOT NULL,
    UserId INT NOT NULL,

    CONSTRAINT fk_company FOREIGN KEY (CompanyId) REFERENCES COMPANY
(ID),
    CONSTRAINT fk_user FOREIGN KEY (UserId) REFERENCES USERS(ID)
);

CREATE TABLE TEAM
(
    Id SERIAL PRIMARY KEY,
    CompanyID INT NOT NULL,
    Name VARCHAR
    (100),

    CONSTRAINT fk_team_company FOREIGN KEY (CompanyID) REFERENCES COMPANY(ID)
);


CREATE TABLE USER_TEAM
(
    TeamId INT NOT NULL,
    UserId INT NOT NULL,

    CONSTRAINT fk_team FOREIGN KEY (TeamId) REFERENCES TEAM
    (Id),
    CONSTRAINT fk_user FOREIGN KEY
    (UserId) REFERENCES USERS
    (ID)
);