version: '3.3'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=Pwd1
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
